version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
    groups:
      docker-actions:
        patterns:
          - "docker/*"
      security-actions:
        patterns:
          - "aquasecurity/*"
          - "github/codeql-action*"
      github-actions:
        patterns:
          - "actions/*"
          - "gautamkrishnar/*"
          - "gaurav-nelson/*"
          - "DavidAnson/*"
