name: Docker Image CI

on:
  schedule:
    - cron: '31 16 * * 3'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-type:
          - cli
          - fpm
          - apache
#          - zts
        php-version: 
          - '8.2'
          - '8.1'
          - '8.0'
          - '7'
        php-base-os: 
          - bullseye
          - alpine
        exclude:
          - php-type: apache
            php-base-os: alpine
#    if: "!contains(github.event.head_commit.message, '[skip nix]')"
  
    steps:
    - 
      name: Repo Name
      id: repo-name
      run: echo "::set-output name=value::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
    - 
      name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2
      id: qemu
      with:
        platforms: amd64,arm64
    - 
      name: Docker Setup Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Login to DockerHub registry
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Log into ghcr.io registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Login to Quay.io registry
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
    -
      name: Build and test docker image
      uses: docker/build-push-action@v4
#      env: |
#          VERSION=${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
#          BASEOS=${{ matrix.php-base-os }}
      with:
        load: true
        tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.value }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VERSION=${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
          BASEOS=${{ matrix.php-base-os }}
    -
      name: Test php
      if: matrix.php-type != 'apache'
      run: |
        docker run --rm docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.value }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }} -v
        docker run --rm docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.value }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }} -m
    -
      name: Test apache
      if: matrix.php-type == 'apache'
      run: |
        docker run --rm docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.value }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }} -v
        docker run --rm docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.value }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }} -l
    - 
      name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: image
        image-ref: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.value }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
        format: 'sarif'
#        template: '@/contrib/sarif.tpl'
        output: 'trivy-results-${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}.sarif'
        severity: 'CRITICAL,HIGH'
        hide-progress: false
    - 
      name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results-${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}.sarif'
    - 
      name: Build and push Docker debian image
      uses: docker/build-push-action@v4
#      env: |
#          VERSION=${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
#          BASEOS=${{ matrix.php-base-os }}
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VERSION=${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
          PHPVERSION=${{ matrix.php-version }}
          BASEOS=${{ matrix.php-base-os }}
        tags: |
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.value }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
          ghcr.io/kingpin/${{ steps.repo-name.outputs.value }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
          quay.io/kingpinx1/${{ steps.repo-name.outputs.value }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}

