name: Docker Image CI

on:
  schedule:
    - cron: '31 16 * * 3'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-type:
          - cli
          - fpm
          - apache
        php-version: 
          - '8.2'
          - '8.1'
          - '8.0'
          - '7'
        php-base-os: 
          - bullseye
          - alpine
        exclude:
          - php-type: apache
            php-base-os: alpine
#    if: "!contains(github.event.head_commit.message, '[skip nix]')"
  
    steps:
    - 
      name: Print env
      run: env | sort
    -
      name: Checkout source
      uses: actions/checkout@v3.3.0
      with:
        # Repository name with owner. For example, actions/checkout
        repository: ${{ github.repository }}
        token: ${{ github.token }}
    -
      name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2
      id: qemu
      with:
        platforms: amd64,arm64,arm
    - 
      name: Docker Setup Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Login to DockerHub registry
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Log into ghcr.io registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Login to Quay.io registry
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
    -
      name: Build and test docker image
      uses: docker/build-push-action@v4
#      env: |
#          VERSION=${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
#          BASEOS=${{ matrix.php-base-os }}
      with:
        load: true
#        tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
        tags: ${{ github.event.repository.name }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VERSION=${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
          PHPVERSION=${{ matrix.php-version }}
          BASEOS=${{ matrix.php-base-os }}
    -
      name: Test php
      if: matrix.php-type != 'apache'
      run: |
        docker run --rm ${{ github.event.repository.name }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }} -v
        docker run --rm ${{ github.event.repository.name }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }} -m
    -
      name: Test apache
      if: matrix.php-type == 'apache'
      run: |
        docker run --rm ${{ github.event.repository.name }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }} -v
        docker run --rm ${{ github.event.repository.name }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }} -l
    - 
      name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: image
        image-ref: ${{ github.event.repository.name }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
        format: 'sarif'
        severity: 'CRITICAL,HIGH'
        hide-progress: false
        output: 'trivy-results-${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}.sarif'
    - 
      name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results-${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}.sarif'
#    -
#      name: Delete all containers from package without tags
#      uses: Chizkiyahu/delete-untagged-ghcr-action@v2
#      with:
#        token: ${{ secrets.PAT_TOKEN }}
#        repository_owner: ${{ github.repository_owner }}
#        repository: ${{ github.repository }}
#        package_name: php-docker
#        untagged_only: true
#        owner_type: org # or user
#        except_untagged_multiplatform: true
#    - 
#      name: Build and push Docker image
#      uses: docker/build-push-action@v4
##      env: |
#          VERSION=${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
#          BASEOS=${{ matrix.php-base-os }}
#      with:
#        platforms: linux/amd64,linux/arm64,linux/arm/v7
#        push: true
#        cache-from: type=gha
#        cache-to: type=gha,mode=max
#        build-contexts: |
#          ${{ github.event.repository.name }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}=docker-image://${{ github.event.repository.name }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
#        build-args: |
#          VERSION=${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
#          PHPVERSION=${{ matrix.php-version }}
#          BASEOS=${{ matrix.php-base-os }}
#        tags: |
#          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
#          ghcr.io/kingpin/${{ github.event.repository.name }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
#          quay.io/kingpinx1/${{ github.event.repository.name }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
    - 
      name: Push To Registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ github.event.repository.name }}:${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
        tags: ${{ matrix.php-version }}-${{ matrix.php-type }}-${{ matrix.php-base-os }}
        registry: quay.io/kingpinx1
