name: Github Action keepalive
on:
  schedule:
    - cron: "0 13 * * *"

jobs:
  create-keepalive-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Keepalive Workflow
          # You may pin to the exact commit or the version.
          # uses: gautamkrishnar/keepalive-workflow@c85efc9567a3dadb9b9d4e116aa891f76c0ef7e6
          uses: gautamkrishnar/keepalive-workflow@latest
          with:
            # GitHub access token with Repo scope
            gh_token: ${{ github.token }}
            # Commit message used while committing to the repo
            commit_message: Actions keepalive auto commit
            # Username used while committing to the repo
            committer_username: Service-Bot
            # Email id used while committing to the repo
            committer_email: git@kpsh.us
            # Time elapsed from the last commit to trigger a new automated commit (in days)
            time_elapsed: 55
            # Defines if the workflow pushes the changes automatically
            auto_push: true
